[project]
additional_flags = "-DMINIMP4_TRANSCODE_SPS_ID -DMP4D_TRACE_TIMESTAMPS -DMP4D_TRACE_SUPPORTED -DMP4D_64BIT_SUPPORTED -DMP4D_AVC_SUPPORTED -DMP4D_INFO_SUPPORTED -DMP4D_TIMESTAMPS_SUPPORTED -DMINIMP4_IMPLEMENTATION -DMP4D_PRINT_INFO_SUPPORTED"
